version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "4500:4500"
    environment:
      - MONGO_URI=mongodb+srv://ourpremium0_db_user:Akilan123@cluster0.adzhtgu.mongodb.net/role-auth
      - PORT=4500
      - SECRET=AKI
      - REFRESH=KABI

  frontend:
    build: ./frontend/client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:4500
   